export const SAVE_ACCOMMODATION_REQUEST = 'SAVE_ACCOMMODATION_REQUEST';
export const FETCH_ACCOMMODATION_REQUEST = 'FETCH_ACCOMMODATION_REQUEST';
export const UPDATE_ACCOMMODATION_REQUEST = 'UPDATE_ACCOMMODATION_REQUEST';
export const DELETE_ACCOMMODATION_REQUEST = 'DELETE_ACCOMMODATION_REQUEST';
export const ACCOMMODATION_SUCCESS = 'ACCOMMODATION_SUCCESS';
export const ACCOMMODATION_FAILURE = 'ACCOMMODATION_FAILURE';