export const SAVE_POINT_REQUEST = 'SAVE_POINT_REQUEST';
export const FETCH_POINT_REQUEST = 'FETCH_POINT_REQUEST';
export const UPDATE_POINT_REQUEST = 'UPDATE_POINT_REQUEST';
export const DELETE_POINT_REQUEST = 'DELETE_POINT_REQUEST';
export const POINT_SUCCESS = 'POINT_SUCCESS';
export const POINT_FAILURE = 'POINT_FAILURE';