export const SAVE_TRIP_REQUEST = 'SAVE_TRIP_REQUEST';
export const FETCH_TRIP_REQUEST = 'FETCH_TRIP_REQUEST';
export const UPDATE_TRIP_REQUEST = 'UPDATE_TRIP_REQUEST';
export const DELETE_TRIP_REQUEST = 'DELETE_TRIP_REQUEST';
export const TRIP_SUCCESS = 'TRIP_SUCCESS';
export const TRIP_FAILURE = 'TRIP_FAILURE';