export const SAVE_PERSON_REQUEST = 'SAVE_PERSON_REQUEST';
export const FETCH_PERSON_REQUEST = 'FETCH_PERSON_REQUEST';
export const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST';
export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const PERSON_SUCCESS = 'PERSON_SUCCESS';
export const PERSON_FAILURE = 'PERSON_FAILURE';